### ISSUE TITLE
warning_email_addr and warning_mode in BE, not in FE

### ISSUE THREAD

**Issue by Jpsy** [TYPO3-Documentation/TYPO3CMS-Guide-Security#1]
Mind the [BE] instead of [FE] in both cases:

1.

> warning_email_addr
> ...
> The PHP variable reads: $TYPO3_CONF_VARS[‘FE’][‘warning_email_addr’]

...should read...

> The PHP variable reads: $TYPO3_CONF_VARS[‘BE’][‘warning_email_addr’]

2.

> warning_mode
> ...
> The PHP variable reads: $TYPO3_CONF_VARS[‘FE’][‘warning_mode’]

...should read...

> The PHP variable reads: $TYPO3_CONF_VARS[‘BE’][‘warning_mode’]

**Comment by Chrissitopher** [comment]
Thanks for the note - that is a valid objection: https://github.com/TYPO3/TYPO3.CMS/search?utf8=%E2%9C%93&q=warning_email_addr&type=Code and https://github.com/TYPO3/TYPO3.CMS/search?utf8=%E2%9C%93&q=warning_mode&type=Code

**Comment by Chrissitopher** [comment]
Fixed with https://github.com/TYPO3-Documentation/TYPO3CMS-Guide-Security/commit/3abc229f8456795d146ce4172d6fdb6765d4cdd6
