### ISSUE TITLE
2x chapter titled "Other services"

### ISSUE THREAD

**Issue by schams-net** [TYPO3-Documentation/TYPO3CMS-Guide-Security#10]
**Chapter "Guidelines for System Administrators"**  
We are using "Other services" as (sub-)chapter titles twice. It would possibly sound better, if we could find a replacement for one of them.

> Note: issue copied from https://forge.typo3.org/issues/32907

**Comment by lolli42** [comment]
https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/commit/db84455e29ddb203651873ef3225d2a7ebafa722
