### ISSUE TITLE
Extend Security Guide by a chapter for developers

### ISSUE THREAD

**Issue by schams-net** [TYPO3-Documentation/TYPO3CMS-Guide-Security#11]
Several attempts have been made in the past to extend the TYPO3 Security Guide by a chapter for developers (*Guidelines for Extension Developers*). Some suggestions were for example:

* Information on SQL injections and Cross Site Scripting
* Explain process how to report a security issue in own extension to the Security Team
* Highlight that a fix for a security issue should be the only change in a release
* Explain the policy of "least disclosure" (used by the Security Team)
* List/summarize typical security vulnerabilities in PHP code (see CWE/SANS Most Dangerous Software Errors)
* Describe how to prevent these errors (maybe show code examples?)
* Explain which typical TYPO3 API functions should be used (?)
* Explain different HTML contexts and which API methods we have to sanitize values.
* Do not use second argument of `getLL()`
* Explain how FE session handling should be done by developers

The chapter should also include how to avoid SQLi properly, how to avoid XSS and a general recommendation to always use the TYPO3 API for validation, escaping and encoding.

It is best practice to make sure you always know which values are safe for output to the browser (htmlspecialchars, quoteJS) and which are not. A general rule we follow is to prepare variables in a raw form (putting together a title, a link or similar) and doing the actual encoding/safety later when outputting it. Another thing would be to make sure to typecast an integer-variable to (int) when you add it to HTML-output and not rely on that "some earlier part" would have made sure it's only a number.

https://forge.typo3.org/issues/50165
https://forge.typo3.org/issues/31672
https://forge.typo3.org/issues/71699
https://forge.typo3.org/issues/71701
https://forge.typo3.org/issues/79575
https://forge.typo3.org/issues/68167

**Comment by sypets** [comment]
I think this is a good idea. It might not be too much work, because the information is mostly already there, both the general information about security invulnerabilities and specific information about what to do in TYPO3. 

I would always try to not duplicate the information if good resources already exist, but link to it.

**Comment by lolli42** [comment]
With the integration of this repository into https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi - we could even better link to existing docs und just bundle the stuff in a 'for developers' chapter again. for instance the database API has good hints about proper quoting / prepared statements.

I'd opt to move this issue over to https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi

**Comment by lolli42** [comment]
Moved to core api with https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/330
