### ISSUE TITLE
Add advice regarding php executables in fileadmin

### ISSUE THREAD

**Issue by schams-net** [TYPO3-Documentation/TYPO3CMS-Guide-Security#12]
All files and folders can and should be write protected for the webserver/php user. However, `fileadmin/` and `typo3temp/` and `uploads/` cannot be write protected be definition. These folders should be excluded in the webserver configuration from executing PHP files.

Unconfirmed suggestion:  
> "*In a standard setup, TYPO3 CMS does not require to write into any directories other than fileadmin, typo3temp, typo3conf and upload. These directories can and should be write protected for the webserver/PHP user. Depending on the individual setup it is also recommended to prevent executing PHP files in the fileadmin and upload directory.*"

> Note: originally posted by Helmut Hummel as https://forge.typo3.org/issues/73031

**Comment by lolli42** [comment]
I think it's a good idea to move that issue over to https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi

**Comment by lolli42** [comment]
Moved to core api as https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/329
