### ISSUE TITLE
Replace occurrences of $TYPO3_CONF_VARS

### ISSUE THREAD

**Issue by schams-net** [TYPO3-Documentation/TYPO3CMS-Guide-Security#15]
Consider to update occurrences of `$TYPO3_CONF_VARS` and similar, to `$GLOBALS['TYPO3_CONF_VARS']` for example.

It should be consistent with other official documentation.

> Note: originally posted as https://forge.typo3.org/issues/42636

**Comment by DanielSiepmann** [comment]
Also checked some more documentations:
- https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/264/
- https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-TSconfig/pull/78/
- https://github.com/TYPO3-Documentation/TYPO3CMS-Guide-Installation/pull/22

**Comment by DanielSiepmann** [comment]
I'll already close this issue as all necessary changes are already provided in the above Pull Requests.
