### ISSUE TITLE
Status of dutch (nl) version?

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Guide-Security#16]
In the version selector, a dutch (nl) version of the manual is selectable: https://docs.typo3.org/typo3cms/SecurityGuide/nl-nl/latest/

This has several issues:

- Most of it is in English
- The nl branch does not exist in the repository on Github
- The layout is shot

If this version does not exist / is outdated, I would suggest removing it from rendering.

**Comment by schams-net** [comment]
The Dutch version is a translation of the English version. I don't know who created it and I suspect he/she never finished it. As a consequence, nobody feels _responsible_ and I totally agree with @sypets that this should be removed completely.

If someone takes over the Dutch translation (or any other language) and makes sure, it is complete and in high quality, it can be added back.

**Comment by schams-net** [comment]
As discussed with @marble (Martin Bless), we deleted the incomplete, outdated Dutch version from the documentation on 14/May/2018.
