### ISSUE TITLE
TYPO3 v9: Clear-text passwords not longer possible

### ISSUE THREAD

**Issue by schams-net** [TYPO3-Documentation/TYPO3CMS-Guide-Security#19]
Several changes to the processing of user passwords and storage have been applied in TYPO3 version 9.3, see `Important-85026-SaltedpasswordsChanges.rst` for details. Consider to document security-related changes.

▸ Clear-text passwords are not longer possible in TYPO3 v9.

**Comment by schams-net** [comment]
In TYPO3 v9.4, MD5 hashed passwords are not longer possible.

**Comment by lolli42** [comment]
'security' chapter of "TYPO3 Explained" no longer contains mentions of md5
