### ISSUE TITLE
TYPO3 v9: Scheduler task to disable/delete FE/BE users on inactivity

### ISSUE THREAD

**Issue by schams-net** [TYPO3-Documentation/TYPO3CMS-Guide-Security#20]
Several changes to the processing of user passwords and storage have been applied in TYPO3 version 9.3, see `Important-85026-SaltedpasswordsChanges.rst` for details. Consider to document security-related changes.

▸ Scheduler task to disable/delete FE/BE users on inactivity

> As a best practice on the principle of data minimisation, inactive frontend and backend users should be removed from the database. [...] The "Table garbage collection task" scheduler task can be configured to fully remove those inactive or deleted users from the system. See scheduler documentation for details on this task.

**Comment by lolli42** [comment]
I linked to the password hashing docs that explains details with https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/commit/c69df8a5ddd276f2695182db94f3c7ccc795538f
