### ISSUE TITLE
TYPO3 v9: Argon2 password hashing algorithm support

### ISSUE THREAD

**Issue by schams-net** [TYPO3-Documentation/TYPO3CMS-Guide-Security#21]
Several changes to the processing of user passwords and storage have been applied in TYPO3 version 9.3, see `Important-85026-SaltedpasswordsChanges.rst` for details. Consider to document security-related changes.

▸ Integrators can select the preferred password hashing algorithm depending on their preference and PHP version and setup.

> The system extension “Salted Passwords” takes care of the passwords of frontend and backend users in TYPO3. This extension now supports the PHP Password Hashing API, which introduces the Argon2 hashing algorithm. Integrators can now select the password hashing method "Standard PHP password hashing (bcrypt)" or "Standard PHP password hashing (argon2i)" in the configuration of the Salted Passwords extension via the Extension Manager. Password hashes of existing users are automatically updated as required, as soon as users log in.

**Comment by lolli42** [comment]
Removed the hints for rsaauth and saltedpasswords with https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/commit/c69df8a5ddd276f2695182db94f3c7ccc795538f
