### ISSUE TITLE
Invalid mailing list link

### ISSUE THREAD

**Issue by nostadt** [TYPO3-Documentation/TYPO3CMS-Guide-Security#22]
https://docs.typo3.org/typo3cms/SecurityGuide/GeneralInformation/AnnouncementOfUpdates/Index.html

On this page look for `You can subscribe at http://lists.typo3.org/cgi- bin/mailman/listinfo/typo3-announce` and try to open this link.

I receive `lists.typo3.org hat die Verbindung abgelehnt.` aka connection refused.

Browser: Chrome
OS: ubuntu

**Comment by schams-net** [comment]
Acknowledged. TYPO3 mailing lists server (`lists.typo3.org`) has been shut down now (this was planned for a long time). I am in contact with the TYPO3 Server Team and Security Team to clarify the new _official_ channel for security bulletins (which then requires an update of the Security Guide).

**Comment by schams-net** [comment]
Update: server shut down was just temporary due to massive mailing list subscription attempts. TYPO3 Server Team has re-activated the server, which is up'n running again now.

However, the server will be decommissioned sooner or later.

**Comment by schams-net** [comment]
Follow up sent: https://typo3.slack.com/archives/C0K5MU94J/p1537022196000100

**Comment by lolli42** [comment]
It's true that lists.typo3.org still does not provide https ... There is nothing we can do about here with this ticket at the moment. I'll go ahead and close it for now.
