### ISSUE TITLE
TYPO3 v9: Prevent .sqlite files from downloading

### ISSUE THREAD

**Issue by schams-net** [TYPO3-Documentation/TYPO3CMS-Guide-Security#23]
TYPO3 can use SQLite databases since version 9.4 (see [feature #85256](https://forge.typo3.org/issues/85256)). In this setup, the database is stored in a single file, rather than on a database server such as MySQL, MariaDB or PostgreSQL. Depending on the setup, this file can be located under `typo3conf/` with a randomly generated filename.

The Security Guide should point that out and recommend to use a proper web server configuration to prevent access to `*.sqlite` files additionally. The example Apache and IIS (`.htaccess` and `web.config` respectively) shipped with TYPO3 contain appropriate configuration lines.

**Comment by marble** [comment]
Maybe the *.sqlite file can and should be placed somewhere outside the webspace?

**Comment by schams-net** [comment]
Well, yes, in a perfect world this file is located **outside** the webroot (this is the case in a composer-based setup for example). However, the core team explicitly pointed out that there is a chance that this is not the case in every installation and system administrators are advised to check this and possibly take appropriate actions to prevent access to this file.

Therefore, I'd say that this is a security-related recommendation, which belongs into the TYPO3 Security Guide. A recommendation to store this file outside the webroot if possible should also be included of course.

**Comment by lolli42** [comment]
An according patch has been pushed with https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/commit/1f2846ac921dc7656aae0aacb0ca8bc8496b25cf
