### ISSUE TITLE
Remove/shorten section about the TYPO3 version policy

### ISSUE THREAD

**Issue by schams-net** [TYPO3-Documentation/TYPO3CMS-Guide-Security#32]
Explanation about **TYPO3 CMS versions and lifecycle** should be documented somewhere else, not as lengthy as it currently is in the Security Guide. The security-related information in this section are only how long and which versions are maintained and receive security updates.

This is a low priority task and the details about the TYPO3 versions should moved to a different TYPO3 documentation before removing them from the Security Guide.

**Comment by lolli42** [comment]
With the merge of this repository into "TYPO3 Explained" (old: "Core API"), this part is now at a better place. We could still think about rewording / shortening / moving this section later, but I think a general information about the version and release strategy is ok at this place.

I'll close the issue for now.
